import { aboutApi } from "./AboutApi";
import {
  instituteMasterFunction,
  admissionOngoingListFunction,
  getAdmissionDetailsFunction,
  websiteInfoGetByInstituteFunction,
  getNoticeInstituteFunction,
  oneNoticeDetailFunction,
  getDocumentByAdmissionFuction,
  admissionGetSiteInfoFunction,
  libraryGetSiteInfoFunction,
  departmentGetSiteInfoFunction,
  allDepartmentFunction,
  departmentAllStaffFunction,
  insAllStaffFunction,
  getAllBookByLibraryFunction,
  oneBookDetailFunction,
  getAllFeesStructureFunction,
  oneFeeStructureDetailFunction,
  getHostInstituteFunction,
  getAllEnquiryListFunction,
  getScholarshipListAdmissionFunction,
  oneApplication,
  getAcademicModuleFunction,
  getNssModuleFunction,
  getFacilitiesModuleFunction,
} from "./about_query_mutation";
const aboutApiDynamic = aboutApi.injectEndpoints({
  endpoints: (builder) => ({
    instituteMaster: instituteMasterFunction(builder),
    admissionOngoingList: admissionOngoingListFunction(builder),
    getAdmissionDetails: getAdmissionDetailsFunction(builder),
    websiteInfoGetByInstitute: websiteInfoGetByInstituteFunction(builder),
    getNoticeInstitute: getNoticeInstituteFunction(builder),
    oneNoticeDetail: oneNoticeDetailFunction(builder),
    getDocumentByAdmission: getDocumentByAdmissionFuction(builder),
    admissionGetSiteInfo: admissionGetSiteInfoFunction(builder),
    libraryGetSiteInfo: libraryGetSiteInfoFunction(builder),
    departmentGetSiteInfo: departmentGetSiteInfoFunction(builder),
    allDepartment: allDepartmentFunction(builder),
    departmentAllStaff: departmentAllStaffFunction(builder),
    getAllBookByLibrary: getAllBookByLibraryFunction(builder),
    oneBookDetail: oneBookDetailFunction(builder),
    getAllFeesStructure: getAllFeesStructureFunction(builder),
    oneFeeStructureDetail: oneFeeStructureDetailFunction(builder),
    getHostInstitute: getHostInstituteFunction(builder),
    getAllEnquiryList: getAllEnquiryListFunction(builder),
    getScholarshipListAdmission: getScholarshipListAdmissionFunction(builder),
    getOneApplication: oneApplication(builder),
    getAcademicModuleInfo: getAcademicModuleFunction(builder),
    getNssModuleInfo: getNssModuleFunction(builder),
    getFacilitiesInfo: getFacilitiesModuleFunction(builder),
    insAllStaffFunction: insAllStaffFunction(builder),
  }),
});

export const {
  useInstituteMasterQuery,
  useAdmissionOngoingListQuery,
  useGetAdmissionDetailsQuery,
  useWebsiteInfoGetByInstituteQuery,
  useGetNoticeInstituteQuery,
  useOneNoticeDetailQuery,
  useGetDocumentByAdmissionQuery,
  useAdmissionGetSiteInfoQuery,
  useLibraryGetSiteInfoQuery,
  useDepartmentGetSiteInfoQuery,
  useAllDepartmentQuery,
  useDepartmentAllStaffQuery,
  useGetAllBookByLibraryQuery,
  useOneBookDetailQuery,
  useGetAllFeesStructureQuery,
  useOneFeeStructureDetailQuery,
  useGetHostInstituteQuery,
  useGetAllEnquiryListQuery,
  useGetScholarshipListAdmissionQuery,
  useGetOneApplicationQuery,
  useGetAcademicModuleInfoQuery,
  useGetNssModuleInfoQuery,
  useGetFacilitiesInfoQuery,
  useInsAllStaffFunctionQuery,
} = aboutApiDynamic;
